<html>
<head>
    <title>Main</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="stylesheet" type="text/css" href="/style.css">
    <style type="text/css">
        A {
            text-decoration: none;
            color: forestgreen;
        }
        A:hover {
            text-decoration: underline;
            color: yellowgreen;
        }

    </style>
</head>
<body>
<div>
    <h2><a href="/news" >Ship's log</a></h2>
    <h2><a href="/private-news" >Add route</a></h2>
    <h2><a href="/check" >Check route!!!!</a></h2>
    <td><p><img src="cherep.jpeg" width="517" height="521"> </p></td>
</div>
</body>
</html>