version: '2.20.3'
services:
  nginx:
    image: nginx:latest
    container_name: start_page
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/scx/services/start-page:/usr/share/nginx/html
