CREATE DATABASE IF NOT EXISTS LOGDB;
USE LOGDB;
CREATE TABLE IF NOT EXISTS TASK (ID UUID primary key, DATE date, DESCRIPTION varchar(255) NOT NULL,
DESTINATION varchar(255) NOT NULL, NAME varchar(255) NOT NULL, STATUS varchar(255) NOT NULL,
ACCESSID varchar(255));
