CREATE DATABASE IF NOT EXISTS weapons;
USE weapons;
CREATE TABLE IF NOT EXISTS ship_weapon (id INT NOT NULL AUTO_INCREMENT, zavod_name VARCHAR(30) NOT NULL, weapon_name VARCHAR(25) NOT NULL, serial_number VARCHAR(40), CONSTRAINT ship_weapon_pk PRIMARY KEY (id));
GRANT ALL PRIVILEGES ON *.* TO 'ctf'@'%' IDENTIFIED BY 'try_hack_me' WITH GRANT OPTION;
